### ISSUE TITLE
Running request.deny() throws error

### ISSUE THREAD

**Issue by yohanesyuen** [copleykj/socialize-friendships#10] opened 2015-09-13 08:50 UTC
After running `request.deny()` in Firefox 40.0.3 on Ubuntu 14.04 LTS I got the following error

```
16:35:30.239 update failed: getErrorObject@http://localhost:3000/packages/aldeed_collection2.js?fdc7f0975dd1b3446ea4afd5f820cb1242a521af:409:15
doValidate@http://localhost:3000/packages/aldeed_collection2.js?fdc7f0975dd1b3446ea4afd5f820cb1242a521af:392:13
Mongo.Collection.prototype[methodName]@http://localhost:3000/packages/aldeed_collection2.js?fdc7f0975dd1b3446ea4afd5f820cb1242a521af:194:20
@http://localhost:3000/packages/matb33_collection-hooks.js?84a1c8cf4708b40e4c95f8e059ef1a0bdb5f5897:423:20
CollectionHooks.extendCollectionInstance/</collection[method]@http://localhost:3000/packages/matb33_collection-hooks.js?84a1c8cf4708b40e4c95f8e059ef1a0bdb5f5897:143:1
BaseModel.prototype.update@http://localhost:3000/packages/socialize_base-model.js?8938e7c01a5774c0085007917afd232a414f0877:160:9
Request.prototype.deny@http://localhost:3000/packages/socialize_friendships.js?f90f9d4a486a3b0e3941480edfcde71b45e47d88:238:5
["click .reject-friendship"]@http://localhost:3000/client/views/userProfile.coffee.js?be4c7eb6373e16e18433f4da9e2842934fedea38:62:14
Template.prototype.events/eventMap2[k]</</<@http://localhost:3000/packages/blaze.js?a5c324925e5f6e800a4c618d71caf2848b53bf51:3502:18
Template._withTemplateInstanceFunc@http://localhost:3000/packages/blaze.js?a5c324925e5f6e800a4c618d71caf2848b53bf51:3476:12
Template.prototype.events/eventMap2[k]</<@http://localhost:3000/packages/blaze.js?a5c324925e5f6e800a4c618d71caf2848b53bf51:3501:1
attached_eventMaps/</</</<@http://localhost:3000/packages/blaze.js?a5c324925e5f6e800a4c618d71caf2848b53bf51:2543:22
Blaze._withCurrentView@http://localhost:3000/packages/blaze.js?a5c324925e5f6e800a4c618d71caf2848b53bf51:2197:12
attached_eventMaps/</</<@http://localhost:3000/packages/blaze.js?a5c324925e5f6e800a4c618d71caf2848b53bf51:2542:1
HandlerRec/this.delegatedHandler</<@http://localhost:3000/packages/blaze.js?a5c324925e5f6e800a4c618d71caf2848b53bf51:839:14
jQuery.event.dispatch@http://localhost:3000/packages/jquery.js?dd8bac56f8fd3666d433d2285ae01e52597cc51a:4697:15
jQuery.event.add/elemData.handle@http://localhost:3000/packages/jquery.js?dd8bac56f8fd3666d433d2285ae01e52597cc51a:4366:6
1 meteor.js:888:11
```

Below is the code that was calling the function

``` coffeescript
'click .reject-friendship': (e, tpl) ->
    user = this.user
    friendRequest = Request.collection.findOne
      userId: Meteor.userId()
      requesterId: user._id
    if friendRequest
      friendRequest.deny()
```

**Comment by copleykj** [comment] 2015-09-15 02:26
I am unable to reproduce this. As a note, you don't generally need to check if there is a request as you are doing. In this case since you have a user, you can call the `user.denyFriendshipRequest` and this will all be taken care of.

``` javascript
'click .reject-friendship': (e, tpl) ->
    this.user.denyFriendshipRequest()
```

**Comment by copleykj** [comment] 2015-09-15 02:26
If you can create a minor reproduction of this issue, I can have a look and try to figure out what the issue may be.

**Comment by copleykj** [comment] 2015-11-22 06:47
I'm closing this for now. Feel free to reopen if you can provide a working reproduction.

**Closed as completed by copleykj** 2015-11-22 06:47 UTC
